project:
  type: website
  render:
    - /slides/formation_light.qmd
    - /slides/formation_full.qmd
    - index.qmd
    - "/cards/**/*.qmd"

website:
  title: "Formation aux bonnes pratiques `Git` et `R`"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/light.html
        text: Version courte
      - href: slides/complete.html
        text: Version longue
    background: "#4758AB"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
