project:
  type: website
  render: 
    - slides/index.qmd
    - slides/formation_light.qmd
    - slides/formation_full.qmd

website:
  title: "today"
  navbar:
    left:
      - href: slides/index.html
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
