project:
  type: website
  render:
    - /slides/formation_light.qmd
    - /slides/formation_full.qmd
    - index.qmd
    - "/cards/**/*.qmd"

website:
  title: "Formation aux bonnes pratiques"
  navbar:
    left:
      - href: index.qmd
        text: Home
    background: "#4758AB"

format:
  html:
    theme: cosmo
    css: styles.scss
    toc: true
