name: Publish slides

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - name: Publish slides
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          to: html
          path: slides/formation_light.qmd
          output-dir: light
      - name: Render slides (full version)
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html
          path: slides/formation_full.qmd
          output-dir: full
          target: gh-pages
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
